### PR TITLE
feat: Support pytest>8.0.2

### LINKED ISSUE #1: pytest-keyring is broken if using pytest > 8.0.2
If I use latest pytest version with pytest-keyring, I get an error message that FixtureDef has no argument fixturemanager:

FixtureDef.__init__() got an unexpected keyword argument 'fixturemanager'

This change was done by [this commit](https://github.com/pytest-dev/pytest/commit/372c17e22899e8e676e105dae714e897426bef86).

Workaround: pip install pytest==8.0.2

### PR DESCRIPTION
**Pull request by tomasfarias**
Support pytest>8.0.2 after breaking change introduced in https://github.com/pytest-dev/pytest/commit/372c17e22899e8e676e105dae714e897426bef86.

Moreover, some other nice changes:
* Bumped versions of everything.
* Use top level `pytest` for typing hints as everything is re-exported.

Closes #1

### CODE REVIEW

**Comment by tomasfarias** [comment]
Semver recommends not bumping major version if requiring a new version of dependency: https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api.

Since this is a bugfix, should be a patch bump for us.
